spring:
  config:
    import: "optional:file:.env"

  server:
    port: 8081

grpc:
  client:
    GLOBAL:
      address: ${GRPC_HOST:localhost:50051}
      negotiation-type: plaintext

    push:
      batch-size: ${BATCH_SIZE:100}
